{{- if .Values.secret.enabled }}
{{- range $secret := .Values.secrets }}                                                                 
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
type: {{ $secret.type }}
stringData:
  {{- range $data := $secret.data }} 
  {{ $data }}
  {{- end -}}
{{ end -}}
{{ end -}}